id: P414DB504
initial_creation_type: ocr
source_metadata:
  volumes:
    fa83584cc2fe4568984b12535568ff85:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: གཏན་ཚིགས་ཀྱི་འཁོར་ལོ་གཏན་ལ་དབབ་པ།
      total_pages: 1198
      volume_number: 97
